# Generated by Django 3.0.5 on 2020-04-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rectifi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('data', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RectifyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RectifyRequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectifi.Image')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectifi.RectifyRequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
