# Generated by Django 3.0.5 on 2020-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectifi', '0002_auto_20200420_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
