# Generated by Django 3.0.5 on 2020-04-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectifi', '0003_auto_20200421_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.BinaryField(editable=True),
        ),
    ]
