# Generated by Django 3.0.5 on 2020-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectifi', '0006_auto_20200421_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectifyrequest',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('PRC', 'Processing'), ('BAD', 'Aborted due to input error'), ('YAY', 'Completed')], default='SUB', max_length=32),
        ),
    ]
