# Generated by Django 3.0.5 on 2020-04-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rectifi', '0007_rectifyrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectifyRequestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=512)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectifi.Image')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectifi.RectifyRequest')),
            ],
        ),
    ]
